### ISSUE TITLE
Looking into reviving this project

### ISSUE THREAD

**Issue by AlexGitDocs** [garethfenn/Soloqueue#1]
Hey,

I show this project on CurseForge and followed it all the way here. After all the new WoW news and people requesting this type of functionality, even more, I was looking into making an addon that will allow it. I see that you attempted it back in 2017 and wanted to ask if you will like to try and revive it? I don't know if you play WoW anymore.

Let me know! It will be great to have a chat about the main challenges too if possible.

Thanks
Alejandro | _Discord:_ DocTiK3r#0488

**Comment by garethfenn** [comment]
Hi Alejandro,

Sure. I'm not interested in updating the project myself but I'm happy to answer questions and help where possible. You're free to take the code and create a new a project/addon.

You can contact me here: garethfenn87@gmail.com

Cheers,
Gareth
